### ISSUE TITLE
rultor merge didn't work correctly

### ISSUE THREAD

**Issue by Graur** [objectionary/dejump#75]
> @rultor merge

@graur @mikhaillipanin Oops, I failed. You can see the full log [here](https://www.rultor.com/t/27615-1288900202) (spent 14s)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 1758131
+ echo '2.0-SNAPSHOT BUILD'
2.0-SNAPSHOT BUILD
+ date
Mon 24 Oct 2022 01:33:45 PM CEST
+ uptime
 13:33:45 up 117 days, 15:34,  0 users,  load average: 0.06, 0.03, 0.03
+ cat
com.rultor.spi.Profile: There is no 'merge' section in .rultor.yml
	at com.rultor.agents.req.StartsRequest.docker(StartsRequest.java:350)
	at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:255)
	at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:148)
	at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:200)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:178)
	at com.rultor.Routine.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.safe(Routine.java:173)
	at com.rultor.Routine.run(Routine.java:141)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler.lambda./run.sh(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)

+ exit -1
'cid' file is absent, most probably the Docker container wasn't started correctly
```

_Originally posted by @rultor in https://github.com/objectionary/dejump/issues/73#issuecomment-1288901455_

**Comment by Graur** [comment]
@MikhailLipanin I thin we can solve this by creating a master branch, similar to this: https://github.com/yegor256/rultor/issues/1356

**Comment by Graur** [comment]
@MikhailLipanin Nope

**Comment by MikhailLipanin** [comment]
fixed
